[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc_2025"
path = "src/lib.rs"

[[bin]]
name = "aoc-2025"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"

